name: "Add MCP server"
description: "Submit your MCP server to the Matrix Hub catalog (no fork needed)."
labels: ["submission", "mcp"]
title: "Add server: <short name>"
body:
- type: input
id: slug
attributes:
label: Folder slug
description: "Will create servers/<slug>/"
placeholder: "my-awesome-mcp"
validations:
required: true
- type: input
id: id
attributes:
label: Server ID
placeholder: repo-agent
validations:
required: true
- type: input
id: name
attributes:
label: Server Name
placeholder: Repo
validations:
required: true
- type: input
id: version
attributes:
label: Version
placeholder: 0.1.0
validations:
required: true
- type: dropdown
id: transport
attributes:
label: Transport
options: ["SSE", "STDIO"]
validations:
required: true
- type: input
id: url
attributes:
label: Server URL (SSE)
placeholder: http://127.0.0.1:6288/sse
- type: input
id: repo
attributes:
label: Repo (git)
placeholder: https://github.com/you/your-mcp.git
- type: input
id: ref
attributes:
label: Ref (tag or commit SHA)
placeholder: v0.1.0 or f01c4503...
- type: textarea
id: summary
attributes:
label: Summary
- type: textarea
id: description
attributes:
label: Description
- type: markdown
attributes:
value: |
**Pro tip:** If you used the `/publish` page, it can also open a prefilled issue that already contains `manifest.json` and `index.json` in code blocks. The bot supports both the form above and the prefilled JSON body.
