name: "Add MCP server"
description: "Submit your MCP server to the Matrix Hub catalog (no fork needed)."
labels: ["submission", "mcp"]
title: "Add server: <short name>"
body:
  - type: input
    id: slug
    attributes:
      label: Folder slug
      description: "A unique identifier used in the URL. Will create `servers/<slug>/`. Use lowercase letters, numbers, and hyphens."
      placeholder: "my-awesome-mcp"
    validations:
      required: true

  - type: input
    id: id
    attributes:
      label: Server ID
      description: "The unique identifier for the server."
      placeholder: "repo-agent"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Server Name
      description: "The human-readable name of the server."
      placeholder: "Repo Agent"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "The version number of your server (e.g., SemVer)."
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      description: "The communication protocol the server uses."
      options:
        - "SSE"
        - "STDIO"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Server URL (SSE)
      description: "**Required only if you selected the `SSE` transport.**"
      placeholder: "http://127.0.0.1:6288/sse"

  - type: input
    id: repo
    attributes:
      label: Repo (git)
      description: "**Required only if you selected the `STDIO` transport.** The git repository URL."
      placeholder: "https://github.com/you/your-mcp.git"

  - type: input
    id: ref
    attributes:
      label: Ref (tag or commit SHA)
      description: "**Required only if you selected the `STDIO` transport.**"
      placeholder: "v0.1.0 or f01c4503..."

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "A brief, one-sentence summary of what your server does."

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A more detailed description of your server. You can use Markdown."

  - type: markdown
    attributes:
      value: |
        **Pro tip:** If you used the `/publish` page, it can also open a prefilled issue that already contains `manifest.json` and `index.json` in code blocks. The bot supports both the form above and the prefilled JSON body.
